title: "What do we need today?"
author: Peter Github User
email: fajag13774@yektara.com
description: "This blog site is intended to provide a platform for you to air your thoughts in terms of current day back & frontend website development for commercial purpose. Ideally, you'll justify your opinion as succinctly as possible. This should be just a light-hearted foray into the question of: What-to-learn-next?" 


# social links
twitter_username: PeterEasterbro1 # DO NOT include the @ character, or else the build will fail!
github_username:  Peter-Easterbrook # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: modernist
